In [1]:
# Allow relative package imports
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [2]:
import pricing.blackscholes as bs

In [4]:
from mpl_toolkits.mplot3d import axes3d
import matplotlib.pyplot as plt
import numpy as np

In [5]:
sigma = 0.50
r = 0.01

In [20]:
curr_prices = np.array(
    [np.arange(80, 120, 2)] * len(np.arange(80, 120, 2))
)

In [37]:
strike_prices = np.array(
    [np.arange(80, 120, 2)] * len(np.arange(80, 120, 2))
)

In [38]:
Z = np.zeros((20, 20))        
for i, price in enumerate(curr_prices[0]):
    for j, strike in enumerate(strike_prices[0]):
        Z[i][j] = bs.callPrice(price, strike, 0.03, .55, 1)


In [40]:
%matplotlib qt
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(strike_prices, curr_prices.transpose(), Z)
plt.show()

In [29]:
axes3d.get_test_data(1)

(array([[-30., -20., -10.,   0.,  10.,  20.],
        [-30., -20., -10.,   0.,  10.,  20.],
        [-30., -20., -10.,   0.,  10.,  20.],
        [-30., -20., -10.,   0.,  10.,  20.],
        [-30., -20., -10.,   0.,  10.,  20.],
        [-30., -20., -10.,   0.,  10.,  20.]]),
 array([[-30., -30., -30., -30., -30., -30.],
        [-20., -20., -20., -20., -20., -20.],
        [-10., -10., -10., -10., -10., -10.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [ 10.,  10.,  10.,  10.,  10.,  10.],
        [ 20.,  20.,  20.,  20.,  20.,  20.]]),
 array([[-9.82064017e-03, -1.19639890e-01, -5.36188786e-01,
         -8.84025856e-01, -5.36188786e-01, -1.19639890e-01],
        [-1.19639843e-01, -1.45751201e+00, -6.53211598e+00,
         -1.07696384e+01, -6.53211503e+00, -1.45751094e+00],
        [-5.35172034e-01, -6.52729956e+00, -2.92602828e+01,
         -4.82376751e+01, -2.92393221e+01, -6.50361544e+00],
        [-4.73838989e-01, -8.82629001e+00, -4.23628013e+01,
         -6.80792672e

In [34]:
(curr_prices, strike_prices, Z)

(array([[ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
         106, 108, 110, 112, 114, 116, 118],
        [ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
         106, 108, 110, 112, 114, 116, 118],
        [ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
         106, 108, 110, 112, 114, 116, 118],
        [ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
         106, 108, 110, 112, 114, 116, 118],
        [ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
         106, 108, 110, 112, 114, 116, 118],
        [ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
         106, 108, 110, 112, 114, 116, 118],
        [ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
         106, 108, 110, 112, 114, 116, 118],
        [ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
         106, 108, 110, 112, 114, 116, 118],
        [ 80,  82,  84,  86,  88,  90,  92,  94,